# Generated by Django 4.0.4 on 2022-06-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.IntegerField()),
                ('imagen_producto', models.ImageField(null=True, upload_to='Carrito')),
                ('usuario', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'db_Carrito',
            },
        ),
        migrations.CreateModel(
            name='CarritoHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_his', models.IntegerField()),
                ('nombre_his', models.CharField(max_length=100)),
                ('precio_hist', models.IntegerField()),
                ('imagen_hist', models.ImageField(null=True, upload_to='Carrito')),
                ('usuario_hist', models.CharField(max_length=200)),
                ('cantidad_hist', models.IntegerField()),
                ('oorden', models.IntegerField()),
            ],
            options={
                'db_table': 'db_CarritoHist',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'db_comuna',
            },
        ),
        migrations.CreateModel(
            name='EstadoSeguimiento',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'db_EstadoSeguimiento',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('user', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'db_Suscripcion',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_productos', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoProducto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadoseguimiento')),
            ],
            options={
                'db_table': 'db_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
            options={
                'db_table': 'db_producto',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('usuario', models.CharField(max_length=200)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadoseguimiento')),
            ],
            options={
                'db_table': 'db_Historial',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comuna')),
            ],
            options={
                'db_table': 'db_cliente',
            },
        ),
    ]
